# frozen_string_literal: true

require "mail"

module Octonotify
  class Mailer
    class DeliveryError < Octonotify::Error
      attr_reader :failed_recipients

      def initialize(failed_recipients)
        @failed_recipients = failed_recipients
        super("Failed to deliver to #{failed_recipients.size} recipient(s)")
      end
    end

    def initialize(config:, delivery_method: nil)
      @config = config
      @delivery_method = delivery_method || build_smtp_delivery
    end

    def send_digest(events)
      return if events.empty?

      body = build_body(events)
      subject = build_subject(events)

      failed = {}
      @config.to.uniq.each do |recipient|
        send_email(to: recipient, subject: subject, body: body)
      rescue StandardError => e
        failed[recipient] = e
      end

      raise DeliveryError, failed unless failed.empty?
    end

    private

    def build_smtp_delivery
      host = ENV.fetch("OCTONOTIFY_SMTP_HOST", nil)
      raise Octonotify::ConfigError, "OCTONOTIFY_SMTP_HOST environment variable is required" if host.nil? || host.empty?

      username = ENV.fetch("OCTONOTIFY_SMTP_USERNAME", nil)
      password = ENV.fetch("OCTONOTIFY_SMTP_PASSWORD", nil)

      smtp_settings = {
        address: host,
        port: parse_smtp_port(ENV.fetch("OCTONOTIFY_SMTP_PORT", nil)),
        enable_starttls_auto: true
      }

      if username && !username.empty?
        if password.nil? || password.empty?
          raise Octonotify::ConfigError, "OCTONOTIFY_SMTP_PASSWORD is required when OCTONOTIFY_SMTP_USERNAME is set"
        end

        smtp_settings[:user_name] = username
        smtp_settings[:password] = password
        smtp_settings[:authentication] = :plain
      end

      [:smtp, smtp_settings]
    end

    def parse_smtp_port(value)
      str = value.to_s.strip
      return 587 if str.empty?

      port = Integer(str, 10)
      return port if port.between?(1, 65_535)

      raise Octonotify::ConfigError, "OCTONOTIFY_SMTP_PORT must be a valid TCP port (1-65535)"
    rescue ArgumentError
      raise Octonotify::ConfigError, "OCTONOTIFY_SMTP_PORT must be a valid TCP port (1-65535)"
    end

    def send_email(to:, subject:, body:)
      from = @config.from
      delivery = @delivery_method

      mail = Mail.new do
        from    from
        to      to
        subject subject
        body    body
      end

      if delivery.is_a?(Array)
        mail.delivery_method(*delivery)
      else
        mail.delivery_method(delivery)
      end
      mail.deliver
    end

    def build_subject(events)
      repo_count = events.map(&:repo).uniq.size
      event_count = events.size

      if repo_count == 1
        "[Octonotify] #{event_count} new event#{"s" if event_count > 1} in #{events.first.repo}"
      else
        "[Octonotify] #{event_count} new event#{"s" if event_count > 1} in #{repo_count} repositories"
      end
    end

    def build_body(events)
      grouped = events.group_by(&:repo)
      timezone = @config.timezone_info

      lines = []
      lines << "GitHub Activity Digest"
      lines << ("=" * 50)
      lines << ""

      grouped.keys.sort.each do |repo|
        repo_events = grouped[repo].sort_by(&:time).reverse
        lines << "## #{repo}"
        lines << "   https://github.com/#{repo}"
        lines << ""

        repo_events.each do |event|
          lines << format_event(event, timezone)
          lines << ""
        end
      end

      lines << ("-" * 50)
      lines << "Generated by Octonotify"

      lines.join("\n")
    end

    def format_event(event, timezone)
      local_time = timezone.to_local(event.time)
      time_str = local_time.strftime("%Y-%m-%d %H:%M %Z")

      lines = []
      lines << "  [#{event_type_label(event.type)}] #{event.title}"
      lines << "  #{event.url}"
      lines << "  Time: #{time_str}"

      case event.type
      when "release"
        lines << "  Tag: #{event.extra[:tag_name]}" if event.extra[:tag_name]
      when "pull_request_merged"
        lines << "  Author: #{event.author}" if event.author
        lines << "  Merged by: #{event.extra[:merged_by]}" if event.extra[:merged_by]
      when "pull_request_created", "issue_created"
        lines << "  Author: #{event.author}" if event.author
      end

      lines.join("\n")
    end

    def event_type_label(type)
      case type
      when "release" then "Release"
      when "pull_request_merged" then "PR Merged"
      when "pull_request_created" then "PR Created"
      when "issue_created" then "Issue Created"
      else type
      end
    end
  end
end
